[frontend]
34.203.234.228 COURSE=Ansible DURATION=1.5hrs TRAINER=satyam ansible_user=ec2-user ansible_password=DevOps321
34.228.64.21   COURSE=Variables DURATION=4hrs TRAINER=satyam ansible_user=ec2-user ansible_password=DevOps321

[local]
localhost 

[all]
52.91.219.206 ansible_user=ec2-user ansible_password=DevOps321
100.53.170.80 ansible_user=ec2-user ansible_password=DevOps321

[local:vars]
COURSE=Ansible
TRAINER=Satyam
DURATION=1.5HR
GREETING="Hello from Inventory"